server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/treasure_hunter
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jooq:
    sql-dialect: POSTGRES

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka